
## You only need to modify this if you're
## going to rebuild tinyvm.srec.

BINDIR = /usr/local/bin
BINPREFIX = h8300-hms-
LIBRCX_HOME = /home/local/david/java/h8300/librcx
JAVA = java

export BINDIR
export BINPREFIX
export LIBRCX_HOME
export CLASSPATH
